services:
  ldap:
    build:
      context: ../
      args:
        BASE_IMAGE: openldap-build
    volumes:
      - ./seed:/seed
    ports:
      - 389:389
      - 636:636
    #tty: true
    #entrypoint: ["/bin/bash"]
    environment:
      OTHER: ''
      BUILTIN_MODULES: 'accesslog,pcache'
      BUILTIN_SCHEMAS: 'misc,cosine'
  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 10443:443
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:['ldap://ldap:389','ldaps://ldap:636']"
